// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2e3WpOPX9INImDmHgqg0GZ4OY6Zcj-24',
    appId: '1:526305938678:web:3421a9eedfbc379fc4f0d7',
    messagingSenderId: '526305938678',
    projectId: 'writeread-de965',
    authDomain: 'writeread-de965.firebaseapp.com',
    storageBucket: 'writeread-de965.firebasestorage.app',
    measurementId: 'G-D1EZCJ672E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7IdLO8ZdGLurYCtRPaJnrMAYT_jzriGw',
    appId: '1:526305938678:android:9be5997b534d8ce6c4f0d7',
    messagingSenderId: '526305938678',
    projectId: 'writeread-de965',
    storageBucket: 'writeread-de965.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCElEDyAh83Mc8BjqDo3DWbEzuZkLhyC00',
    appId: '1:526305938678:ios:8a9dedc9625354a1c4f0d7',
    messagingSenderId: '526305938678',
    projectId: 'writeread-de965',
    storageBucket: 'writeread-de965.firebasestorage.app',
    iosClientId: '526305938678-t2qu47it3e6ml23j1pm1fr8hdm4opks1.apps.googleusercontent.com',
    iosBundleId: 'com.example.writereadAdminPanel',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCElEDyAh83Mc8BjqDo3DWbEzuZkLhyC00',
    appId: '1:526305938678:ios:8a9dedc9625354a1c4f0d7',
    messagingSenderId: '526305938678',
    projectId: 'writeread-de965',
    storageBucket: 'writeread-de965.firebasestorage.app',
    iosClientId: '526305938678-t2qu47it3e6ml23j1pm1fr8hdm4opks1.apps.googleusercontent.com',
    iosBundleId: 'com.example.writereadAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2e3WpOPX9INImDmHgqg0GZ4OY6Zcj-24',
    appId: '1:526305938678:web:34dda59401c8f238c4f0d7',
    messagingSenderId: '526305938678',
    projectId: 'writeread-de965',
    authDomain: 'writeread-de965.firebaseapp.com',
    storageBucket: 'writeread-de965.firebasestorage.app',
    measurementId: 'G-WY0E2PYHJK',
  );
}
