// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs6uXiC8ViuXJSvtcc4uB4Jm8kOewLbXM',
    appId: '1:436595745003:web:3b1dda92ba3faa73f0deae',
    messagingSenderId: '436595745003',
    projectId: 'comics-app-e163a',
    authDomain: 'comics-app-e163a.firebaseapp.com',
    storageBucket: 'comics-app-e163a.firebasestorage.app',
    measurementId: 'G-MFNFBEDS3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkzabN2ljGa0WKDOX3N3peu0qIDUng_mA',
    appId: '1:436595745003:android:e80f4b0b414d8862f0deae',
    messagingSenderId: '436595745003',
    projectId: 'comics-app-e163a',
    storageBucket: 'comics-app-e163a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6scluhEhAg-3QbMCU8EohIC2gNviAB_k',
    appId: '1:436595745003:ios:e807a30a6372b526f0deae',
    messagingSenderId: '436595745003',
    projectId: 'comics-app-e163a',
    storageBucket: 'comics-app-e163a.firebasestorage.app',
    iosClientId: '436595745003-45lpbl3fai088dvkqdjk468rm23i9m1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.writereadAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6scluhEhAg-3QbMCU8EohIC2gNviAB_k',
    appId: '1:436595745003:ios:e807a30a6372b526f0deae',
    messagingSenderId: '436595745003',
    projectId: 'comics-app-e163a',
    storageBucket: 'comics-app-e163a.firebasestorage.app',
    iosClientId: '436595745003-45lpbl3fai088dvkqdjk468rm23i9m1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.writereadAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClwBoC-jWRUPJ1S2mtBCvR14kqmSr5tBQ',
    appId: '1:436595745003:web:6d045199efd83ce7f0deae',
    messagingSenderId: '436595745003',
    projectId: 'comics-app-e163a',
    authDomain: 'comics-app-e163a.firebaseapp.com',
    storageBucket: 'comics-app-e163a.firebasestorage.app',
    measurementId: 'G-7J8X2FB3WY',
  );
}
